### PR TITLE
Select the correct instance of mirador when using multi-mirador on a

### PR DESCRIPTION
**Pull request by mejackreed**
page config

Fixes an issue where a multi-mirador setup isn't able to configure for the nth mirador

### CODE REVIEW

**Comment by jkeck** [comment]
This seems to not quite fix the issue entirely.  I'm still seeing an issue where saving the changes in a modal can modify the mirador config of the wrong block.  This is how I've been able to reproduce.

1. Create a mirador widget (configuring in the modal) and save page.
1. Edit that page and create a new Mirador widget above the one created in the previous step (again configure in the modal and save the page).
1. Edit the page again, and click the button to configure the modal in the previous step, make a change and save changed (as well as save the page).

The behavior that I'm seeing is that a version of the mirador configuration for the top viewer is being written to both mirador_config fields.  I'm going to push up a commit that I believe addresses this.

**Comment by jkeck** [comment]
One thing that neither of these commits address is that when editing a page w/ multiple mirador widgets you cannot configure multiple widgets in the same edit screen (you simply get whatever the first mirador viewer loaded is).

**Comment by mejackreed** [comment]
Thanks for the add on commit @jkeck ! I'm not sure exactly how to recreate that second comment you are mentioning. But this is an improvement thanks!

**Comment by jkeck** [comment]
@mejackreed 👀 
mirador-widget-wonky

**Comment by mejackreed** [comment]
/tableflip "works for me"

try to get it to fail

**Comment by aeschylus** [comment]
This fix is working for me locally.

**Comment by camillevilla** [comment]
This is an improvement over yesterday's bug, but I'm getting the same issue as @jkeck:
viewer-preview

**Comment by camillevilla** [comment]
Behold! A squished bug 🐛
multi-mirador

**Pull request merged**
